rootPageId: 1
base: /
languages:
  -
    title: English
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
errorHandling: {  }
routes: {  }
routeEnhancers:
  BwGuildOffer:
    type: Extbase
    extension: BwGuild
    plugin: Offerlist
    routes:
      -
        routePath: '/{offer}'
        _controller: 'Offer::show'
        _arguments:
          offer: offer
    defaultController: 'Offer::show'
    aspects:
      offer:
        type: PersistedAliasMapper
        tableName: tx_bwguild_domain_model_offer
        routeFieldName: slug
baseVariants: {  }
